# Generated by Django 5.2.10 on 2026-01-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_acceso_registrado_por_acceso_sede_usuario_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='programa_formacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sede_principal',
            field=models.CharField(blank=True, choices=[('CEGAFE', 'CEGAFE'), ('SANTA_CLARA', 'SANTA CLARA'), ('ITEDRIS', 'ITEDRIS'), ('GASTRONOMIA', 'GASTRONOMIA')], max_length=20, null=True),
        ),
    ]
