# Generated by Django 6.0.2 on 2026-02-12 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0004_notificacion_passwordresetotp'),
    ]

    operations = [
    migrations.AlterField(
        model_name='turno',
        name='inicio',
        field=models.DateTimeField(default=django.utils.timezone.now),
    ),
]
