# Generated by Django 6.0.2 on 2026-02-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0005_alter_turno_inicio_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.CheckConstraint(condition=models.Q(('fin__isnull', True), ('fin__gte', models.F('inicio')), _connector='OR'), name='turno_fin_gte_inicio_or_null'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activo', True), ('fin__isnull', True)), models.Q(('activo', False), ('fin__isnull', False)), _connector='OR'), name='turno_activo_fin_coherente'),
        ),
    ]
